/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include"stdio.h"
#include "platform_t.h"

#define RCC_base      0x40021000
#define GPIO_PA_base  0x40010800

#define   APB2ENR    *(vuint32_t *)(0x40021000+0x18)
#define   CRH_R      *(vuint32_t *)(0x40010800+0x04)
#define   ODR_R      *(vuint32_t *)(0x40010800+0x0C)

typedef union {
	vuint32_t allpins ;
	volatile struct
	{
		vuint32_t reserved:13;
		vuint32_t pin13:1;
	}Spin;
}Uodr_R_t;
extern void Hard_Fault_handler(){

} ;

volatile Uodr_R_t * ODR=(volatile Uodr_R_t *)(0x40010800+0x0C);
vsint32_t test_data=3;//to test .data (not effect in the project)
uint8 test1_data[5]={2,3,3};//to test .data (not effect in the project)
vsint32_t test_bss;//to test .bss (not effect in the project)
vsint8_t test1_bss;//to test .bss (not effect in the project)
int main(void)
{
	APB2ENR |=1<<2;
	CRH_R &=0xff0fffff;
	CRH_R |=0x00200000;
	while(1)
	{
		//ODR_R |=1<<13;
		ODR->Spin.pin13=1;
		for(int x=0;x<=100000;x++);
		//ODR_R &=~(1<<13);
		ODR->Spin.pin13=0;
		for(int x=0;x<=100000;x++);
	}
}
