/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
This software used to toggle led by manage clock input
 ******************************************************************************
 */

#include"stdio.h"
#include "platform_t.h"

#define RCC_base      0x40021000

#define   RCC_APB2ENR      *(vuint32_t *)(0x40021000+0x18)

#define GPIO_PA_base  0x40010800

#define   CRH_R      *(vuint32_t *)(0x40010800+0x04)
#define   ODR_R      *(vuint32_t *)(0x40010800+0x0C)

typedef union {
	vuint32_t allpins ;
	volatile struct
	{
		vuint32_t reserved:13;
		vuint32_t pin13:1;
	}Spin;
}Uodr_R_t;

volatile Uodr_R_t * ODR=(volatile Uodr_R_t *)(0x40010800+0x0C);
int main(void)
{
	//enable clock on porta
	RCC_APB2ENR |=1<<2;
	CRH_R &=0xff0fffff;
	CRH_R |=0x00200000;
	while(1)
	{
		//ODR_R |=1<<13;
		ODR->Spin.pin13=1;
		for(int x=0;x<=100000;x++);
		//ODR_R &=~(1<<13);s
		ODR->Spin.pin13=0;
		for(int x=0;x<=100000;x++);
	}
}
