/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software used to toggle led by manage clock input
 * apb2--->2 Mhz
 * apb1--->4 Mhz
 ******************************************************************************
 */

#include"stdio.h"
#include "platform_t.h"

//GPIO
#define GPIO_PA_base  0x40010800
#define   CRH_R      *(vuint32_t *)(GPIO_PA_base+0x04)
#define   ODR_R      *(vuint32_t *)(GPIO_PA_base+0x0C)
#define   CRL_R      *(vuint32_t *)(GPIO_PA_base+0x0)

//RCC
#define RCC_base      0x40021000
#define   RCC_APB2ENR      *(vuint32_t *)(RCC_base+0x18)

//AFIO
#define AFIO_base      0x40010000
#define   AFIO_EXTICR1      *(vuint32_t *)(AFIO_base+0x08)

//EXTI
#define EXTI_base      0x40010400
#define   EXTI_RTSR      *(vuint32_t *)(EXTI_base+0x08)
#define   EXTI_IMR      *(vuint32_t *)(EXTI_base+0x0)
#define   EXTI_PR      *(vuint32_t *)(EXTI_base+0x14)

//NVIC
#define 	NVIC_CortexM3_Set      *(vuint32_t *)(0xE000E100)

void GPIO_INIT(void){
	// GPIO pin13 output--->led
	CRH_R &=0xff0fffff;
	CRH_R |=0x00200000;
	//GPIO Pin0 input--->button
	//CNFy[1:0]: Port A configuration bit 0
	//01: Floating input (reset state)
	CRL_R |=(1<<2);
}
void CLOCK_INIT(void){
	//enable clock on portA
	RCC_APB2ENR |=1<<2;
	//enable clock on AFIO
	/*Bit 0 AFIOEN: Alternate function IO clock enable
	Set and cleared by software.
	0: Alternate Function IO clock disabled
	1: Alternate Function IO clock enabled*/
	RCC_APB2ENR |=1<<0;
	//enable clock on EXTI-->by default enable (becouse not excit in RCC_APB2ENR)

}
void main(void){
	GPIO_INIT();
	CLOCK_INIT();
	/*Bits 15:0 EXTIx[3:0]: EXTI x configuration (x= 0 to 3)
	These bits are written by software to select the source input for EXTIx external interrupt.
	Refer to Section 10.2.5: External interrupt/event line mapping
	0000: PA[x] pin
	0001: PB[x] pin
	0010: PC[x] pin
	0011: PD[x] pin
	0100: PE[x] pin
	0101: PF[x] pin
	0110: PG[x] pin*/
	//enable PA0 to EXTI0
	AFIO_EXTICR1 =0;
    //----------------------

	/*Bits 19:0 TRx: Rising trigger event configuration bit of line x
	0: Rising trigger disabled (for Event and Interrupt) for input line
	1: Rising trigger enabled (for Event and Interrupt) for input line.
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.*/
	//enable rising pin0 --->EXTI0
	EXTI_RTSR |=(1<<0);
	//----------------------

	/*Bits 19:0 MRx: Interrupt Mask on line x
	0: Interrupt request from Line x is masked
	1: Interrupt request from Line x is not masked
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.*/
	//enable mask interrupt pin0 --->EXTI0
	EXTI_IMR |=(1<<0);
	//----------------------

	//enable mask in NVIC
	//irq 6 is irq of EXTI0
	NVIC_CortexM3_Set |=(1<<6);

	while(1);
}
void EXTI0_IRQHandler(void){
	//irq from EXTI0 --PA0--->rising edge
	//toggle led in portA pin 13
	ODR_R ^=(1<<13);
	//---------------------------

	/*Bits 19:0 PRx: Pending bit
	0: No trigger request occurred
	1: selected trigger request occurred
	This bit is set when the selected edge event arrives on the external interrupt line. This bit is
	cleared by writing a ‘1’ into the bit.
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.*/

	//clear pending after finish
	EXTI_PR |=(1<<0);
}
